version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - sbernet
  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sber
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 3
    networks:
      - sbernet
networks:
  sbernet:
    driver: bridge